version: '3.8'

services:
  app-gestionstationski:
    image: cheimadouiss/timesheet-devops:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.datasource.username": "root",
        "spring.datasource.password": "admin",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.H2Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

