version: "3"
services:
  spring-ski:
    image: cyrine382/cyrinegharbi-5bi3-g5-gestionstationski
    ports:
      - "8089:8089"
    networks:
      - station
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/cyrinedata:/var/lib/mysql:rw
    networks:
      - station
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
  front-ski:
    image: cyrine382/cyrinegharbi-5bi3-g5-gestionstationski-front
    ports:
      - "80:80"
    networks:
      - station
    depends_on:
      - spring-ski
      - mysqldb


networks:
  station: