version: '3.8'  # Version de Docker Compose

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE= stationski  # Base de données à créer
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql  # Volume pour persister les données

  app-gestionstationski:
    depends_on:
      - mysqldb
    image: asmalaaribi/gestion-station-ski:1.0.0
    restart: on-failure
    ports:
      - 8081:8081  # Port d'exposition
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://localhost:3306/stationski?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true  # Alloue un terminal virtuel

volumes:
  db:  # Volume pour persister les données de la base de données

