version: '3.8'  # Version de Docker Compose

services:
  app-gestionstationski:
    image: asmalaaribi/gestion-station-ski:1.0.0
    restart: on-failure
    ports:
      - 8081:8081  # Port d'exposition
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.datasource.username": "sa",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.H2Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true  # Alloue un terminal virtuel