
services:
  prometheus:
    image: prom/prometheus
    container_name: root-prometheus-1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - springboot-mysql-network  # Make sure Prometheus is on the same network
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus
      restart: always
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maissembase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_HOST="%"
    volumes:
      - mysql_data:/var/lib/mysql
  springboot-app:
    image: maissemhedfi/gestion-ski:${BUILD_NUMBER}
    container_name: springboot-app
    restart: on-failure
    networks:
      - springboot-mysql-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/maissembase?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
networks:
  springboot-mysql-network:
    driver: bridge
