
services:
  prometheus:
    image: prom/prometheus
    container_name: root-prometheus-1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - springboot-mysql-network  # Make sure Prometheus is on the same network
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus
      restart: always
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maissembase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_HOST="%"
      - SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/maissembase?createDatabaseIfNotExist=true

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - springboot-mysql-network
  springboot-app:
    image: maissemhedfi/gestion-ski:${BUILD_NUMBER}
    container_name: springboot-app
    restart: on-failure
    networks:
      - springboot-mysql-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/maissembase?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - "8089:8089"
    depends_on:
      - mysql
networks:
  springboot-mysql-network:
    driver: bridge
